spring:
    datasource:
        url: jdbc:mysql://localhost:3306/apolo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: false
    mail: 
        host: smtp.gmail.com
        port: 587
        username: apolo.web.page@gmail.com
        password: hfrxcxqpsitsxjcc
        properties:
            mail:
                smtp:              
                    auth: true
                    starttls:
                        required: true
                        enable: true
server:
    port: 8080


